### DISCUSSION TITLE
Text alignment tokens

### DISCUSSION THREAD

**Discussion by GarthDB** [adobe/spectrum-design-data#339] [Q&A] [answered]
# The problem

We don't currently include horizontal text-alignment values in Spectrum Tokens.

# The proposal

We're considering adding some for cases like this in the table component:
![Frame 3675](https://github.com/adobe/spectrum-design-data/assets/125516/8569b398-c464-4bfa-8025-96385f9080f9)

The only potential complication comes from right-to-left and left-to-right language switching. [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align#start) supports logical properties `start`, `center`, and `end` instead of `left`, `center`, and `right`. This allows the alignment to change based on language direction without changing the text-align property.

```yml
---
"$schema": https://json-schema.org/draft/2020-12/schema
"$id": https://opensource.adobe.com/spectrum-tokens/schemas/token-types/text-align.json
title: Text align
description: Sets whether text should be aligned `start`, `center`, or `end`
type: object
allOf:
- "$ref": https://opensource.adobe.com/spectrum-tokens/schemas/token-types/token.json
properties:
  "$schema":
    const: https://opensource.adobe.com/spectrum-tokens/schemas/token-types/text-align.json
  value:
    type: string
    enum:
      - start
      - center
      - end
    default: start
  component: {}
  private: {}
  deprecated: {}
  deprecated_comment: {}
  uuid: {}
```

# Alternatives considered

We've considered the more universal `left`, `center`, and `right` values, but we lose out on the logical option benefits mentioned in the proposal.

# Questions

What about non-web implementations, would logical options cause issues for text-alignment?
